#!/usr/bin/python

import argparse
import boto.ses
from subprocess import Popen, STDOUT
import sys
import tempfile
import traceback

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--from-address', required=True)
    parser.add_argument('--subject', required=True)
    parser.add_argument('--to-address', action='append')
    parser.add_argument('--cc-address', action='append')
    parser.add_argument('--bcc-address', action='append')

    config, args = parser.parse_known_args()

    message = '* Command: \'' + '\' \''.join(args) + '\'\n'
    with tempfile.TemporaryFile() as file:
        try:
            p = Popen(args, stdout=file, stderr=STDOUT)
            p.wait()

            if p.returncode == 0:
                sys.exit(0)

            file.seek(0)
            message += '* Return code: %s\n' % p.returncode
            message += '* Output:\n'
            message += file.read()
            message += '\n\n'
        except:
            message += '* '
            message += traceback.format_exc()

    ses = boto.ses.connect_to_region('us-east-1')
    ses.send_email(config.from_address, config.subject, message,
            config.to_address, config.cc_address, config.bcc_address)
