#!/usr/bin/python
# Terminate instance and scale group down

import boto.ec2.autoscale
import boto.utils

metadata = boto.utils.get_instance_metadata()

REGION = metadata['placement']['availability-zone'][:-1]
INSTANCE = metadata['instance-id']
DECREMENT_CAPACITY = True

autoscale = boto.ec2.autoscale.connect_to_region(REGION)
autoscale.terminate_instance(INSTANCE, DECREMENT_CAPACITY)
